
CREATE TABLE movienight_users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    password VARCHAR NOT NULL
);

CREATE TABLE movienight_lists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    user_id int REFERENCES movienight_users(id) ON DELETE CASCADE NOT NULL
);


CREATE TABLE movienight_movies(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    overview TEXT NOT NULL,
    poster_path TEXT NOT NULL,
    movielist_id int REFERENCES movienight_lists(id) ON DELETE CASCADE NOT NULL,
    votes int NOT NULL
);

